#settings-bro
services:
  settings-bro:
    #image: settings-bro:latest
    build: .
    container_name: settings-bro
    hostname: settings-bro
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
    volumes:
      - ./settings:/app/settings:ro
    networks:
      - spacebro
      - default

networks:
  default:
  spacebro:
    external: true